---
- name: Install and configure MCP Servers
  hosts: all
  gather_facts: true

  tasks:
    - name: Ensure base functionality
      ansible.builtin.include_role:
        name: ansible.mcp_builder.common
        public: true

    - name: Parse mcp_servers input
      ansible.builtin.include_role:
        name: ansible.mcp_builder.common
        tasks_from: parse_mcp_servers
      vars:
        mcp_servers: "github_mcp,azure_mcp,aws_iam_mcp,aws_ccapi_mcp,aws_cdk_mcp,aws_core_mcp" # noqa: var-naming[no-role-prefix]

    - name: Install selected MCP providers
      ansible.builtin.include_role:
        name: "ansible.mcp_builder.{{ item }}"
      loop: "{{ common_mcp_roles }}"
      when: do_installation | default(true)
      vars:
        aws_core_mcp_do_verify: false # TODO - Temporarily disabled. See https://github.com/awslabs/mcp/issues/1947

    - name: Fix ownership of all MCP installations for runtime user
      ansible.builtin.file:
        path: "{{ common_mcp_base_path }}"
        state: directory
        recurse: true
        owner: "{{ common_runtime_user }}"
        group: "{{ common_runtime_user }}"
      when: do_installation | default(true)

    - name: Display installed MCP servers
      ansible.builtin.debug:
        msg: "Installed MCP servers: {{ common_mcp_roles }}"
